name: OpenMod.Rust.Oxide.Redist

on:
  push:
    branches: [ main ]
    paths:
      - 'rust/oxide/redist/**'

jobs:
  build:
    name: "OpenMod.Rust.Oxide.Redist Pack"
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    - uses: nuget/setup-nuget@v2
      with:
        nuget-api-key: ${{ secrets.NUGET_DEPLOY_KEY }}
        nuget-version: '5.x'
    - uses: ./.github/actions/nuget-pack
      id: nuget-pack
      with:
        nuspec_path: rust/oxide/redist/OpenMod.Rust.Oxide.Redist.nuspec
        nuget_key: ${{ secrets.NUGET_DEPLOY_KEY }}
        nuget_push: true
